kafka:
  pool: nav-prod
sqlInstances:
  diskAutoresize: true
  pointInTimeRecovery: true
ingress:
  url: https://tiltakspenger-vedtak.intern.nav.no
cluster: prod-gcp
tenant: nav.no
ROLE_SAKSBEHANDLER: 6c6ce2e8-b2e2-4c4b-8194-215c8e27a5c7
ROLE_BESLUTTER: de518927-f657-4f37-9a64-14fdfd968dd2
ROLE_ADMINISTRATOR: 8478cae3-88d6-4070-a5a6-f06bd36bc50d
ROLE_FORTROLIG: 9ec6487d-f37a-4aad-a027-cd221c1ac32b
ROLE_STRENGT_FORTROLIG: ad7b87a6-9180-467c-affc-20a566b0fec0
ROLE_SKJERMING: e750ceb5-b70b-4d94-b4fa-9d22467b786b
ROLE_DRIFT: 0405ed09-1248-47f7-a6e3-e998bc90feca
