apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: tiltakspenger-vedtak
  namespace: tpts
  labels:
    team: tpts
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 1
    max: 1
  ingresses:
    - https://tiltakspenger-vedtak.dev.intern.nav.no
  liveness:
    path: /isalive
  readiness:
    path: /isready
  kafka:
    pool: nav-dev
  secureLogs:
    enabled: true
