package no.nav.tiltakspenger.saksbehandling.behandling.domene

enum class ManueltBehandlesGrunn {
    SOKNAD_HAR_ANDRE_YTELSER,
    SOKNAD_HAR_LAGT_TIL_BARN_MANUELT,
    SOKNAD_BARN_UTENFOR_EOS,
    SOKNAD_BARN_FYLLER_16_I_SOKNADSPERIODEN,
    SOKNAD_HAR_KVP,
    SOKNAD_INTRO,
    SOKNAD_INSTITUSJONSOPPHOLD,

    SAKSOPPLYSNING_FANT_IKKE_TILTAK,
    SAKSOPPLYSNING_OVERLAPPENDE_TILTAK,
    SAKSOPPLYSNING_MINDRE_ENN_14_DAGER_MELLOM_TILTAK_OG_SOKNAD,
    SAKSOPPLYSNING_ULIK_TILTAKSPERIODE,
    SAKSOPPLYSNING_ANDRE_YTELSER,

    ANNET_APEN_BEHANDLING,
    ANNET_VEDTAK_FOR_SAMME_PERIODE,
    ANNET_HAR_SOKT_FOR_SENT,
    ANNET_ER_UNDER_18_I_SOKNADSPERIODEN,
}
