package no.nav.tiltakspenger.saksbehandling.behandling.domene

enum class ManueltBehandlesGrunn {
    SOKNAD_HAR_ANDRE_YTELSER,
    SOKNAD_HAR_LAGT_TIL_BARN_MANUELT,
    SOKNAD_BARN_UTENFOR_EOS,
    SOKNAD_BARN_FYLLER_16_I_SOKNADSPERIODEN,
    SOKNAD_BARN_FODT_I_SOKNADSPERIODEN,
    SOKNAD_HAR_KVP,
    SOKNAD_INTRO,
    SOKNAD_INSTITUSJONSOPPHOLD,

    SAKSOPPLYSNING_FANT_IKKE_TILTAK,
    SAKSOPPLYSNING_TILTAK_MANGLER_PERIODE,
    SAKSOPPLYSNING_TILTAK_MANGLER_DELTAKELSESMENGDE,
    SAKSOPPLYSNING_TILTAK_MER_ENN_FEM_DAGER_PER_UKE,
    SAKSOPPLYSNING_DELTIDSTILTAK_UTEN_DAGER_PER_UKE,
    SAKSOPPLYSNING_OVERLAPPENDE_TILTAK,
    SAKSOPPLYSNING_MINDRE_ENN_14_DAGER_MELLOM_TILTAK_OG_SOKNAD,
    SAKSOPPLYSNING_ULIK_TILTAKSPERIODE,
    SAKSOPPLYSNING_HAR_IKKE_DELTATT_PA_TILTAK,
    SAKSOPPLYSNING_ANDRE_YTELSER,
    SAKSOPPLYSNING_VEDTAK_I_ARENA,
    SAKSOPPLYSNING_MANGLER_FULLSTENDIG_PERIODE,

    STANS_FANT_IKKE_TILTAKSDELTAKELSE,
    STANS_DELTAKELSEN_ER_IKKE_AVSLUTTET,
    STANS_DELTAKELSEN_MANGLER_SLUTTDATO,
    STANS_SLUTTDATO_ER_IKKE_PASSERT,
    STANS_INGEN_INNVILGEDE_DAGER_ETTER_SLUTTDATO,
    STANS_ANDRE_DELTAKELSER_INNVILGET_ETTER_SLUTTDATO,
    STANS_UTBETALING_KAN_IKKE_IVERKSETTES,
    STANS_KAN_IKKE_SENDES_TIL_BESLUTNING,

    ANNET_APEN_BEHANDLING,
    ANNET_VEDTAK_FOR_SAMME_PERIODE,
    ANNET_HAR_SOKT_FOR_SENT,
    ANNET_ER_UNDER_18_I_SOKNADSPERIODEN,
}
