package no.nav.tiltakspenger.saksbehandling.klage.infra.repo

import no.nav.tiltakspenger.saksbehandling.klage.domene.Klagehjemmel

enum class KlagehjemmelDb {
    ARBEIDSMARKEDSLOVEN_2,
    ARBEIDSMARKEDSLOVEN_13,
    ARBEIDSMARKEDSLOVEN_13_LØNN,
    ARBEIDSMARKEDSLOVEN_13_FJERDE_LEDD,
    ARBEIDSMARKEDSLOVEN_15,
    ARBEIDSMARKEDSLOVEN_17,
    TILTAKSPENGEFORSKRIFTEN_2,
    TILTAKSPENGEFORSKRIFTEN_3,
    TILTAKSPENGEFORSKRIFTEN_5,
    TILTAKSPENGEFORSKRIFTEN_6,
    TILTAKSPENGEFORSKRIFTEN_7,
    TILTAKSPENGEFORSKRIFTEN_8,
    TILTAKSPENGEFORSKRIFTEN_9,
    TILTAKSPENGEFORSKRIFTEN_10,
    TILTAKSPENGEFORSKRIFTEN_11,
    ;

    fun toDomain(): Klagehjemmel = when (this) {
        ARBEIDSMARKEDSLOVEN_2 -> Klagehjemmel.ARBEIDSMARKEDSLOVEN_2
        ARBEIDSMARKEDSLOVEN_13 -> Klagehjemmel.ARBEIDSMARKEDSLOVEN_13
        ARBEIDSMARKEDSLOVEN_13_LØNN -> Klagehjemmel.ARBEIDSMARKEDSLOVEN_13_LØNN
        ARBEIDSMARKEDSLOVEN_13_FJERDE_LEDD -> Klagehjemmel.ARBEIDSMARKEDSLOVEN_13_FJERDE_LEDD
        ARBEIDSMARKEDSLOVEN_15 -> Klagehjemmel.ARBEIDSMARKEDSLOVEN_15
        ARBEIDSMARKEDSLOVEN_17 -> Klagehjemmel.ARBEIDSMARKEDSLOVEN_17
        TILTAKSPENGEFORSKRIFTEN_2 -> Klagehjemmel.TILTAKSPENGEFORSKRIFTEN_2
        TILTAKSPENGEFORSKRIFTEN_3 -> Klagehjemmel.TILTAKSPENGEFORSKRIFTEN_3
        TILTAKSPENGEFORSKRIFTEN_5 -> Klagehjemmel.TILTAKSPENGEFORSKRIFTEN_5
        TILTAKSPENGEFORSKRIFTEN_6 -> Klagehjemmel.TILTAKSPENGEFORSKRIFTEN_6
        TILTAKSPENGEFORSKRIFTEN_7 -> Klagehjemmel.TILTAKSPENGEFORSKRIFTEN_7
        TILTAKSPENGEFORSKRIFTEN_8 -> Klagehjemmel.TILTAKSPENGEFORSKRIFTEN_8
        TILTAKSPENGEFORSKRIFTEN_9 -> Klagehjemmel.TILTAKSPENGEFORSKRIFTEN_9
        TILTAKSPENGEFORSKRIFTEN_10 -> Klagehjemmel.TILTAKSPENGEFORSKRIFTEN_10
        TILTAKSPENGEFORSKRIFTEN_11 -> Klagehjemmel.TILTAKSPENGEFORSKRIFTEN_11
    }

    companion object {
        fun Klagehjemmel.toDb(): KlagehjemmelDb = when (this) {
            Klagehjemmel.ARBEIDSMARKEDSLOVEN_2 -> ARBEIDSMARKEDSLOVEN_2
            Klagehjemmel.ARBEIDSMARKEDSLOVEN_13 -> ARBEIDSMARKEDSLOVEN_13
            Klagehjemmel.ARBEIDSMARKEDSLOVEN_13_LØNN -> ARBEIDSMARKEDSLOVEN_13_LØNN
            Klagehjemmel.ARBEIDSMARKEDSLOVEN_13_FJERDE_LEDD -> ARBEIDSMARKEDSLOVEN_13_FJERDE_LEDD
            Klagehjemmel.ARBEIDSMARKEDSLOVEN_15 -> ARBEIDSMARKEDSLOVEN_15
            Klagehjemmel.ARBEIDSMARKEDSLOVEN_17 -> ARBEIDSMARKEDSLOVEN_17
            Klagehjemmel.TILTAKSPENGEFORSKRIFTEN_2 -> TILTAKSPENGEFORSKRIFTEN_2
            Klagehjemmel.TILTAKSPENGEFORSKRIFTEN_3 -> TILTAKSPENGEFORSKRIFTEN_3
            Klagehjemmel.TILTAKSPENGEFORSKRIFTEN_5 -> TILTAKSPENGEFORSKRIFTEN_5
            Klagehjemmel.TILTAKSPENGEFORSKRIFTEN_6 -> TILTAKSPENGEFORSKRIFTEN_6
            Klagehjemmel.TILTAKSPENGEFORSKRIFTEN_7 -> TILTAKSPENGEFORSKRIFTEN_7
            Klagehjemmel.TILTAKSPENGEFORSKRIFTEN_8 -> TILTAKSPENGEFORSKRIFTEN_8
            Klagehjemmel.TILTAKSPENGEFORSKRIFTEN_9 -> TILTAKSPENGEFORSKRIFTEN_9
            Klagehjemmel.TILTAKSPENGEFORSKRIFTEN_10 -> TILTAKSPENGEFORSKRIFTEN_10
            Klagehjemmel.TILTAKSPENGEFORSKRIFTEN_11 -> TILTAKSPENGEFORSKRIFTEN_11
        }

        fun List<Klagehjemmel>.toDb(): List<KlagehjemmelDb> = this.map { it.toDb() }

        fun List<KlagehjemmelDb>.toDomain(): List<Klagehjemmel> = this.map { it.toDomain() }
    }
}
