WITH
sakz AS (DELETE FROM sak WHERE id = :sak_id RETURNING id),
behandlingz AS (DELETE FROM behandling WHERE sak_id IN (SELECT id FROM sakz) returning soknad_id),
søknadz AS (DELETE FROM søknad WHERE sak_id IN (SELECT id FROM sakz) OR id in (select soknad_id from behandlingz) returning id),
søknad_barnetilleggz AS (DELETE FROM søknad_barnetillegg WHERE søknad_id IN (SELECT id FROM søknadz)),
søknadstiltakz AS (DELETE FROM søknadstiltak WHERE søknad_id IN (SELECT id FROM søknadz)),
rammevedtakz AS (DELETE FROM rammevedtak WHERE sak_id IN (SELECT id FROM sakz)),
meldekortz AS (DELETE FROM meldekortbehandling WHERE sak_id IN (SELECT id FROM sakz)),
meldekort_brukerz AS (DELETE from meldekort_bruker mb WHERE sak_id IN (SELECT id FROM sakz)),
meldekortvedtakz AS (DELETE FROM meldekortvedtak WHERE sak_id IN (SELECT id FROM sakz)),
utbtalingsvedtakz AS (DELETE FROM utbetalingsvedtak WHERE sak_id IN (SELECT id FROM sakz)),
meldekortbehandlingz AS (DELETE from meldekortbehandling mb where sak_id IN (SELECT id FROM sakz)),
meldeperiode AS (delete from meldeperiode m WHERE sak_id IN (SELECT id FROM sakz)),
utbetalingz as (delete from utbetaling u where sak_id in (select id from sakz)),
statistikk_utbetalingz AS (DELETE FROM statistikk_utbetaling WHERE sak_id IN (SELECT id FROM sakz)),
statistikk_meldekortz AS (DELETE FROM statistikk_meldekort WHERE sak_id IN (SELECT id FROM sakz)),
statistikk_stonadz AS (DELETE FROM statistikk_stonad WHERE sak_id IN (SELECT id FROM sakz)),
statistikk_sakz AS (DELETE FROM statistikk_sak WHERE sak_id IN (SELECT id FROM sakz) returning id),
personhendelsez AS (DELETE FROM personhendelse WHERE sak_id IN (SELECT id FROM sakz) returning id),
identhendelsez AS (DELETE FROM identhendelse WHERE sak_id IN (SELECT id FROM sakz) returning id),
tiltaksdeltaker_kafkaz AS (DELETE FROM tiltaksdeltaker_kafka WHERE sak_id IN (SELECT id FROM sakz)),
klagebehandlingz AS (DELETE FROM klagebehandling WHERE sak_id IN (SELECT id FROM sakz)),
klagehendelsez AS (DELETE FROM klagehendelse WHERE sak_id IN (SELECT id FROM sakz)),
klagevedtakz AS (DELETE FROM klagevedtak WHERE sak_id IN (SELECT id FROM sakz))
SELECT id FROM sakz;