package no.nav.tiltakspenger.saksbehandling.ytelser.domene

enum class Ytelsetype(val tekstverdi: String) {
    AAP("Arbeidsavklaringspenger"),
    AFP("Avtalefestet pensjon"),
    ALDERSPENSJON("Alderspensjon"),
    ARBEIDSAVKLARINGSP("Arbeidsavklaringspenger"),
    BARNEPENSJON("Barnepensjon"),
    DAGPENGER("Dagpenger"),
    ENSLIG_FORSORGER("Enslig forsørger"),
    ETTERLATTEPENSJON("Etterlattepensjon"),
    FORELDREPENGER("Foreldrepenger"),
    FORELDREPENREFARBGIV("Foreldrepenger refusjon arbeidsgiver"),
    KOMPENSASJON("Kompensasjon inntektstap"),
    KRIGSPENSJON("Krigspensjon"),
    LONNSKOMPENSASJON("Lønnskompensasjon"),
    OMSTILLINGSSTONAD("Omstillingsstønad"),
    PEN_REINDRIFTSSAMER("Pensjon reindriftssamer"),
    PLEIEPENGER("Pleiepenger"),
    PLEIEPENGERREFARBGIV("Pleiepenger refusjon arbeidgiver"),
    REFUSJON("Refusjon"),
    REFUSJON_PST("Refusjon PST"),
    REFUSJON_SPK("Refusjon SPK"),
    REFUSJONSKRAV("Refusjonskrav"),
    SPK("Statens pensjonkasse"),
    SUPPLERENDE_STONAD("Supplerende_stønad"),
    SYKEPENGER("Sykepenger"),
    SYKEPENGERREFARBGIV("Sykepenger refusjon arbeidsgiver"),
    TJENESTEPENSJON("Tjenestepensjon"),
    UFOREPENSJON("Uførepensjon"),
    UFORETRYGD("Uføretrygd"),
    UTDANNINGSSTONAD("Utdanningsstønad"),
    UKJENT("Ukjent"),
}
