-- Fix invalid ULIDs generated by V214. Those were random bytes encoded as Crockford Base32,
-- but a valid ULID requires a 48-bit millisecond timestamp in the first 10 chars.

CREATE OR REPLACE FUNCTION pg_temp.generate_ulid() RETURNS text AS
$$
DECLARE
    alphabet  text   := '0123456789ABCDEFGHJKMNPQRSTVWXYZ';
    ts_millis bigint;
    result    text   := '';
    rand      bytea;
    i         int;
    bits      int    := 0;
    buffer    int    := 0;
BEGIN
    ts_millis := (extract(epoch from clock_timestamp()) * 1000)::bigint;

    -- Encode 48-bit timestamp as 10 base32 chars (MSB first, 50 bits with 2 leading zero bits)
    FOR i IN REVERSE 9..0
        LOOP
            result := result || substr(alphabet, (((ts_millis >> (i * 5)) & 31) + 1)::int, 1);
        END LOOP;

    -- Encode 80 random bits (10 bytes) as 16 base32 chars
    rand := gen_random_bytes(10);
    FOR i IN 0..9
        LOOP
            buffer := (buffer << 8) | get_byte(rand, i);
            bits := bits + 8;
            WHILE bits >= 5
                LOOP
                    bits := bits - 5;
                    result := result || substr(alphabet, ((buffer >> bits) & 31) + 1, 1);
                END LOOP;
        END LOOP;

    RETURN result;
END;
$$ LANGUAGE plpgsql;

-- Rader der kilde ikke er null ble opprettet etter v214/v215 og har gyldige ULID generert av app-koden
UPDATE tiltaksdeltaker_kafka
SET hendelse_id = 'tiltaksdeltakerhendelse_' || pg_temp.generate_ulid()
WHERE kilde is null;

