package no.nav.tiltakspenger.saksbehandling.klage.domene

enum class Klagehjemmel {
    ARBEIDSMARKEDSLOVEN_2,
    ARBEIDSMARKEDSLOVEN_13,
    ARBEIDSMARKEDSLOVEN_13_LØNN,
    ARBEIDSMARKEDSLOVEN_13_FJERDE_LEDD,
    ARBEIDSMARKEDSLOVEN_15,
    ARBEIDSMARKEDSLOVEN_17,
    TILTAKSPENGEFORSKRIFTEN_2,
    TILTAKSPENGEFORSKRIFTEN_3,
    TILTAKSPENGEFORSKRIFTEN_5,
    TILTAKSPENGEFORSKRIFTEN_6,
    TILTAKSPENGEFORSKRIFTEN_7,
    TILTAKSPENGEFORSKRIFTEN_8,
    TILTAKSPENGEFORSKRIFTEN_9,
    TILTAKSPENGEFORSKRIFTEN_10,
    TILTAKSPENGEFORSKRIFTEN_11,
}
