name: Build, push and deploy to dev (manual)

on:
  workflow_dispatch:

jobs:
  build:
    name: Build and deploy
    uses: ./.github/workflows/.test-and-build.yml
    permissions:
      contents: read
      id-token: write
    with:
      NAIS_ENV: dev
    secrets:
      NAIS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
      SLACK_INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}
  deploy:
    name: Deploy to NAIS (dev)
    needs: build
    uses: ./.github/workflows/.deploy-to-nais.yml
    permissions:
      contents: read
      id-token: write
    with:
      NAIS_ENV: dev
      IMAGE: ${{ needs.build.outputs.IMAGE }}
